import os
import shutil
import subprocess
import asyncio
import time
import json
import random
import math
from typing import Dict, Any, List, Optional
from sqlalchemy.orm import Session

from ..models import Experiment, Result
from .trace_parser import parse_ns2_trace_file

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SIMULATION_DIR = os.path.join(BASE_DIR, "simulation")
TCL_DIR = os.path.join(SIMULATION_DIR, "tcl")
TRACES_DIR = os.path.join(SIMULATION_DIR, "traces")
os.makedirs(TCL_DIR, exist_ok=True)
os.makedirs(TRACES_DIR, exist_ok=True)

# In-memory tracking for active simulation stages
active_simulations: Dict[int, Dict[str, Any]] = {}

class ConnectionManager:
    def __init__(self):
        self.active_sim_connections: Dict[int, List[Any]] = {}
        self.global_connections: List[Any] = []

    async def connect_sim(self, experiment_id: int, websocket: Any):
        await websocket.accept()
        if experiment_id not in self.active_sim_connections:
            self.active_sim_connections[experiment_id] = []
        self.active_sim_connections[experiment_id].append(websocket)

    def disconnect_sim(self, experiment_id: int, websocket: Any):
        if experiment_id in self.active_sim_connections:
            if websocket in self.active_sim_connections[experiment_id]:
                self.active_sim_connections[experiment_id].remove(websocket)
            if not self.active_sim_connections[experiment_id]:
                del self.active_sim_connections[experiment_id]

    async def broadcast_sim(self, experiment_id: int, data: dict):
        if experiment_id in self.active_sim_connections:
            disconnected = []
            for ws in self.active_sim_connections[experiment_id]:
                try:
                    await ws.send_json(data)
                except Exception:
                    disconnected.append(ws)
            for ws in disconnected:
                self.disconnect_sim(experiment_id, ws)

    async def connect_global(self, websocket: Any):
        await websocket.accept()
        self.global_connections.append(websocket)

    def disconnect_global(self, websocket: Any):
        if websocket in self.global_connections:
            self.global_connections.remove(websocket)

    async def broadcast_global(self, data: dict):
        disconnected = []
        for ws in self.global_connections:
            try:
                await ws.send_json(data)
            except Exception:
                disconnected.append(ws)
        for ws in disconnected:
            self.disconnect_global(ws)

ws_manager = ConnectionManager()

def check_ns2_installation() -> Dict[str, Any]:
    """Check if NS-2 is available natively or inside WSL."""
    # 1. Native check
    native_ns = shutil.which("ns")
    if native_ns:
        return {"installed": True, "mode": "native", "path": native_ns, "cmd": ["ns"]}

    # 2. WSL check
    wsl = shutil.which("wsl")
    if wsl:
        try:
            res = subprocess.run(
                ["wsl", "-d", "Ubuntu", "--", "which", "ns"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if res.returncode == 0 and res.stdout.strip():
                return {
                    "installed": True,
                    "mode": "wsl",
                    "path": res.stdout.strip(),
                    "cmd": ["wsl", "-d", "Ubuntu", "--", "ns"]
                }
        except Exception:
            pass

    return {"installed": False, "mode": "none", "path": None, "cmd": []}


def generate_tcl_script(
    experiment_id: int,
    users: int,
    protocol: str,
    bottleneck_bw: str,
    sim_time: float,
    experiment_type: str
) -> str:
    """Generates an NS-2 Tcl simulation script for the university e-learning topology."""
    tcl_filename = f"experiment_{experiment_id}.tcl"
    tcl_path = os.path.join(TCL_DIR, tcl_filename)
    tr_filename = f"experiment_{experiment_id}.tr"
    tr_path = os.path.join(TRACES_DIR, tr_filename).replace("\\", "/")

    # Clean bandwidth string, e.g. "1 Mbps" -> "1Mb"
    bw = bottleneck_bw.replace(" ", "").replace("ps", "").replace("bps", "b")
    if not any(bw.endswith(suffix) for suffix in ["Mb", "Kb", "mb", "kb"]):
        bw = f"{bw}Mb"

    queue_type = "DropTail"
    queue_limit = 25
    if experiment_type == "Leaky Bucket":
        # Simulates Leaky Bucket / RED queue behavior
        queue_type = "RED"
        queue_limit = 35

    proto = protocol.upper()
    server_id = users + 2

    lines = [
        "# NS-2 Simulation Script Generated by EduNet Analyzer",
        f"# Experiment ID: {experiment_id} | Users: {users} | Protocol: {proto}",
        "set ns [new Simulator]",
        "",
        f'set tracefile [open "{tr_path}" w]',
        "$ns trace-all $tracefile",
        "",
        "# Node Definitions",
        f"# Student nodes (0 to {users - 1})",
        f"for {{set i 0}} {{$i < {users}}} {{incr i}} {{",
        "    set n($i) [$ns node]",
        "}",
        f"set r1 [$ns node]      ;# Access Router (ID: {users})",
        f"set r2 [$ns node]      ;# Core Router (ID: {users + 1})",
        f"set server [$ns node]  ;# E-Learning Server (ID: {server_id})",
        "",
        "# Link Topologies",
        f"# Student to Access Router Links (10Mb, 5ms delay)",
        f"for {{set i 0}} {{$i < {users}}} {{incr i}} {{",
        "    $ns duplex-link $n($i) $r1 10Mb 5ms DropTail",
        "}",
        "",
        f"# Campus Core Bottleneck Link (Bandwidth: {bw}, 20ms delay)",
        f"$ns duplex-link $r1 $r2 {bw} 20ms {queue_type}",
        f"$ns queue-limit $r1 $r2 {queue_limit}",
        "",
        f"# Core Router to E-Learning Server Link (100Mb, 2ms delay)",
        f"$ns duplex-link $r2 $server 100Mb 2ms DropTail",
        "",
        "# Traffic Agents Setup",
    ]

    if proto == "TCP":
        lines.extend([
            f"for {{set i 0}} {{$i < {users}}} {{incr i}} {{",
            "    set tcp($i) [new Agent/TCP/Newreno]",
            "    $tcp($i) set window_ 32",
            "    $tcp($i) set packetSize_ 1024",
            "    $ns attach-agent $n($i) $tcp($i)",
            "    set sink($i) [new Agent/TCPSink]",
            "    $ns attach-agent $server $sink($i)",
            "    $ns connect $tcp($i) $sink($i)",
            "    set ftp($i) [new Application/FTP]",
            "    $ftp($i) attach-agent $tcp($i)",
            f"    $ns at [expr 0.1 + ($i * 0.05)] \"$ftp($i) start\"",
            f"    $ns at {sim_time - 0.5} \"$ftp($i) stop\"",
            "}",
        ])
    else: # UDP / CBR
        lines.extend([
            f"for {{set i 0}} {{$i < {users}}} {{incr i}} {{",
            "    set udp($i) [new Agent/UDP]",
            "    $ns attach-agent $n($i) $udp($i)",
            "    set null($i) [new Agent/Null]",
            "    $ns attach-agent $server $null($i)",
            "    $ns connect $udp($i) $null($i)",
            "    set cbr($i) [new Application/Traffic/CBR]",
            "    $cbr($i) set packetSize_ 1024",
            f"    $cbr($i) set rate_ [expr 1.0 / {users}]Mb",
            "    $cbr($i) attach-agent $udp($i)",
            f"    $ns at [expr 0.1 + ($i * 0.05)] \"$cbr($i) start\"",
            f"    $ns at {sim_time - 0.5} \"$cbr($i) stop\"",
            "}",
        ])

    lines.extend([
        "",
        "# Termination Handler",
        f"$ns at {sim_time} \"finish\"",
        "proc finish {} {",
        "    global ns tracefile",
        "    $ns flush-trace",
        "    close $tracefile",
        "    exit 0",
        "}",
        "",
        "$ns run"
    ])

    with open(tcl_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return tcl_path


def generate_calibrated_demo_trace(
    trace_path: str,
    users: int,
    protocol: str,
    data_rate_str: str,
    sim_duration: float,
    experiment_type: str
):
    """
    Generates a physically calibrated, realistic NS-2 trace file (.tr) 
    using discrete event queue modeling for environments without NS-2.
    This guarantees that the trace file exists on disk and is parsed 
    by the genuine NS-2 trace parser.
    """
    server_id = users + 2
    router1_id = users
    router2_id = users + 1

    # Extract target capacity from data_rate_str
    rate_val = 1.0
    if "k" in data_rate_str.lower():
        rate_val = float(''.join(c for c in data_rate_str if c.isdigit() or c == '.') or 512) / 1000.0
    elif "m" in data_rate_str.lower():
        rate_val = float(''.join(c for c in data_rate_str if c.isdigit() or c == '.') or 1.0)

    # Base bottleneck capacity in packets per second (1024 bytes/pkt)
    capacity_pps = (rate_val * 1000000) / (1024 * 8)
    
    # Traffic generation rate per user (bursty or continuous)
    if protocol.upper() == "TCP":
        load_multiplier = 0.85 + min(users * 0.02, 0.45)
    else:
        load_multiplier = 0.95 + min(users * 0.03, 0.70)

    total_offered_rate_pps = capacity_pps * load_multiplier
    user_rate_pps = total_offered_rate_pps / max(users, 1)

    pkt_id = 0
    seq_num = 0
    current_time = 0.1

    queue_capacity = 25 if experiment_type != "Leaky Bucket" else 35
    current_queue = 0
    next_departure_time = 0.1

    lines = []
    
    # Event loop generating trace entries
    while current_time < sim_duration - 0.5:
        # Step through active users
        for u in range(users):
            if current_time >= sim_duration - 0.5:
                break
            
            # Packet inter-arrival time with Poisson/exponential variation
            iat = random.expovariate(user_rate_pps) if user_rate_pps > 0 else 0.05
            current_time += iat
            
            pkt_id += 1
            seq_num += 1
            pkt_type = "tcp" if protocol.upper() == "TCP" else "cbr"
            pkt_size = 1024

            # 1. Enqueue at Student Node '+'
            lines.append(f"+ {current_time:.6f} {u} {router1_id} {pkt_type} {pkt_size} ------- 1 {u}.0 {server_id}.0 {seq_num} {pkt_id}")
            # 2. Dequeue from Student Node '-'
            t_dept = current_time + 0.0008
            lines.append(f"- {t_dept:.6f} {u} {router1_id} {pkt_type} {pkt_size} ------- 1 {u}.0 {server_id}.0 {seq_num} {pkt_id}")
            # 3. Arrive at Router 1 'r'
            t_arr_r1 = t_dept + 0.005 # 5ms link delay
            lines.append(f"r {t_arr_r1:.6f} {u} {router1_id} {pkt_type} {pkt_size} ------- 1 {u}.0 {server_id}.0 {seq_num} {pkt_id}")

            # 4. Bottleneck link Router 1 -> Router 2
            # Check queue occupancy
            if t_arr_r1 < next_departure_time:
                current_queue += 1
            else:
                current_queue = max(0, current_queue - int((t_arr_r1 - next_departure_time) * capacity_pps))

            if current_queue > queue_capacity:
                # Packet drop 'd' at router 1 bottleneck queue!
                lines.append(f"d {t_arr_r1:.6f} {router1_id} {router2_id} {pkt_type} {pkt_size} ------- 1 {u}.0 {server_id}.0 {seq_num} {pkt_id}")
            else:
                # Packet service through bottleneck link
                service_time = 1.0 / capacity_pps
                departure_time = max(t_arr_r1, next_departure_time) + service_time
                next_departure_time = departure_time
                
                # Dequeue from router 1
                lines.append(f"- {departure_time:.6f} {router1_id} {router2_id} {pkt_type} {pkt_size} ------- 1 {u}.0 {server_id}.0 {seq_num} {pkt_id}")
                # Receive at router 2 (20ms delay)
                t_arr_r2 = departure_time + 0.020
                lines.append(f"r {t_arr_r2:.6f} {router1_id} {router2_id} {pkt_type} {pkt_size} ------- 1 {u}.0 {server_id}.0 {seq_num} {pkt_id}")

                # Router 2 to Server (2ms delay)
                t_arr_srv = t_arr_r2 + 0.002
                lines.append(f"r {t_arr_srv:.6f} {router2_id} {server_id} {pkt_type} {pkt_size} ------- 1 {u}.0 {server_id}.0 {seq_num} {pkt_id}")

    with open(trace_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


async def run_simulation_task(experiment_id: int, db_factory):
    """
    Background worker orchestrating the multi-stage simulation pipeline:
    1. PREPARING
    2. GENERATING_TOPOLOGY
    3. RUNNING_NS2
    4. PROCESSING_TRACE
    5. CALCULATING_METRICS
    6. COMPLETED
    """
    db: Session = db_factory()
    try:
        exp = db.query(Experiment).filter(Experiment.id == experiment_id).first()
        if not exp:
            return

        exp.status = "RUNNING"
        db.commit()

        active_simulations[experiment_id] = {
            "status": "RUNNING",
            "progress_percent": 10,
            "current_stage": "PREPARING",
            "stage_message": f"Initializing environment for {exp.name}...",
            "logs": [f"[{time.strftime('%H:%M:%S')}] Started experiment {exp.exp_code}"],
            "error": None
        }
        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])

        await asyncio.sleep(0.6)

        # Stage 2: Generating Topology
        active_simulations[experiment_id]["progress_percent"] = 25
        active_simulations[experiment_id]["current_stage"] = "GENERATING_TOPOLOGY"
        active_simulations[experiment_id]["stage_message"] = f"Constructing campus network topology with {exp.users} student nodes and bottleneck router..."
        active_simulations[experiment_id]["logs"].append(
            f"[{time.strftime('%H:%M:%S')}] Created topology: {exp.users} Students -> Access Router -> Core Router -> LMS Server"
        )
        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])

        tcl_script = generate_tcl_script(
            experiment_id=exp.id,
            users=exp.users,
            protocol=exp.protocol,
            bottleneck_bw=exp.data_rate,
            sim_time=exp.simulation_time,
            experiment_type=exp.experiment_type
        )
        active_simulations[experiment_id]["logs"].append(f"[{time.strftime('%H:%M:%S')}] Generated Tcl script: {os.path.basename(tcl_script)}")
        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])

        await asyncio.sleep(0.8)

        # Stage 3: Running NS-2
        active_simulations[experiment_id]["progress_percent"] = 50
        active_simulations[experiment_id]["current_stage"] = "RUNNING_NS2"
        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])
        
        ns_info = check_ns2_installation()
        tr_filename = f"experiment_{exp.id}.tr"
        tr_path = os.path.join(TRACES_DIR, tr_filename)
        server_id = exp.users + 2

        if not exp.is_demo:
            # LIVE NS-2 EXECUTION
            if not ns_info["installed"]:
                err_msg = "LIVE SIMULATION UNAVAILABLE: NS-2 could not be executed. Please install/configure NS-2 or use Demo Mode."
                active_simulations[experiment_id]["status"] = "FAILED"
                active_simulations[experiment_id]["current_stage"] = "FAILED"
                active_simulations[experiment_id]["error"] = err_msg
                active_simulations[experiment_id]["stage_message"] = "LIVE SIMULATION UNAVAILABLE: NS-2 could not be executed."
                active_simulations[experiment_id]["logs"].append(
                    f"[{time.strftime('%H:%M:%S')}] [ERROR] LIVE SIMULATION UNAVAILABLE"
                )
                active_simulations[experiment_id]["logs"].append(
                    f"[{time.strftime('%H:%M:%S')}] [ERROR] NS-2 binary ('ns' or 'wsl ns') was not detected on your system path."
                )
                active_simulations[experiment_id]["logs"].append(
                    f"[{time.strftime('%H:%M:%S')}] [ERROR] Real-Time mode strictly requires NS-2. Please install NS-2 or use Demo Mode."
                )
                exp.status = "FAILED"
                db.commit()
                await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])
                return

            active_simulations[experiment_id]["stage_message"] = f"Executing live NS-2 binary ({ns_info['mode']}) for {exp.simulation_time}s simulation..."
            active_simulations[experiment_id]["logs"].append(
                f"[{time.strftime('%H:%M:%S')}] Executing command: {' '.join(ns_info['cmd'])} {tcl_script}"
            )
            await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])

            try:
                cmd = list(ns_info["cmd"])
                if ns_info["mode"] == "wsl":
                    wsl_tcl = tcl_script.replace("\\", "/").replace("f:/", "/mnt/f/").replace("F:/", "/mnt/f/")
                    cmd.append(wsl_tcl)
                else:
                    cmd.append(tcl_script)

                proc = await asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE
                )
                stdout, stderr = await proc.communicate()

                if proc.returncode != 0:
                    err_text = stderr.decode('utf-8', errors='ignore')[:300]
                    active_simulations[experiment_id]["status"] = "FAILED"
                    active_simulations[experiment_id]["current_stage"] = "FAILED"
                    active_simulations[experiment_id]["error"] = f"LIVE SIMULATION UNAVAILABLE: NS-2 returned exit code {proc.returncode}."
                    active_simulations[experiment_id]["stage_message"] = "LIVE SIMULATION UNAVAILABLE: NS-2 execution failed."
                    active_simulations[experiment_id]["logs"].append(
                        f"[{time.strftime('%H:%M:%S')}] [ERROR] NS-2 execution failure: {err_text}"
                    )
                    exp.status = "FAILED"
                    db.commit()
                    await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])
                    return
                else:
                    active_simulations[experiment_id]["logs"].append(f"[{time.strftime('%H:%M:%S')}] NS-2 completed successfully with exit code 0")
            except Exception as e:
                active_simulations[experiment_id]["status"] = "FAILED"
                active_simulations[experiment_id]["current_stage"] = "FAILED"
                active_simulations[experiment_id]["error"] = f"LIVE SIMULATION UNAVAILABLE: {str(e)}"
                active_simulations[experiment_id]["stage_message"] = "LIVE SIMULATION UNAVAILABLE: NS-2 process exception."
                active_simulations[experiment_id]["logs"].append(f"[{time.strftime('%H:%M:%S')}] [ERROR] NS-2 exception: {str(e)}")
                exp.status = "FAILED"
                db.commit()
                await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])
                return
        else:
            # Predefined Demo Mode Generation
            active_simulations[experiment_id]["stage_message"] = "Generating discrete-event demo trace records..."
            active_simulations[experiment_id]["logs"].append(
                f"[{time.strftime('%H:%M:%S')}] [DEMO MODE] Simulating discrete packet arrivals and writing trace file..."
            )
            generate_calibrated_demo_trace(tr_path, exp.users, exp.protocol, exp.data_rate, exp.simulation_time, exp.experiment_type)
            exp.is_demo = True

        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])
        await asyncio.sleep(0.8)

        # Stage 4: Processing Trace
        active_simulations[experiment_id]["progress_percent"] = 75
        active_simulations[experiment_id]["current_stage"] = "PROCESSING_TRACE"
        active_simulations[experiment_id]["stage_message"] = "Parsing NS-2 trace file events (+, -, r, d) across all network interfaces..."
        active_simulations[experiment_id]["logs"].append(
            f"[{time.strftime('%H:%M:%S')}] Trace file generated: {os.path.basename(tr_path)} ({os.path.getsize(tr_path)} bytes)"
        )
        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])

        metrics = parse_ns2_trace_file(
            trace_path=tr_path,
            server_node_id=server_id,
            simulation_duration=exp.simulation_time
        )
        active_simulations[experiment_id]["logs"].append(
            f"[{time.strftime('%H:%M:%S')}] Trace parsed: {metrics['packets_sent']} sent, {metrics['packets_received']} received, {metrics['packets_dropped']} dropped"
        )
        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])

        await asyncio.sleep(0.5)

        # Stage 5: Calculating Metrics
        active_simulations[experiment_id]["progress_percent"] = 90
        active_simulations[experiment_id]["current_stage"] = "CALCULATING_METRICS"
        active_simulations[experiment_id]["stage_message"] = "Computing Throughput, End-to-End Latency, Packet Delivery Ratio, and Loss percentages..."
        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])

        # Store in database
        exp.trace_file = tr_path
        exp.status = "COMPLETED"

        summary = (
            f"{exp.protocol} transmission with {exp.users} student nodes achieved "
            f"{metrics['throughput_kbps']} Kbps throughput, {metrics['packet_delivery_ratio']}% PDR, "
            f"and {metrics['average_delay_ms']} ms average delay under {exp.traffic_level} traffic load."
        )

        result = Result(
            experiment_id=exp.id,
            throughput_kbps=metrics["throughput_kbps"],
            packet_loss_percent=metrics["packet_loss_percent"],
            packet_delivery_ratio=metrics["packet_delivery_ratio"],
            average_delay_ms=metrics["average_delay_ms"],
            packets_sent=metrics["packets_sent"],
            packets_received=metrics["packets_received"],
            packets_dropped=metrics["packets_dropped"],
            data_rate_kbps=metrics["data_rate_kbps"],
            time_series_json=json.dumps(metrics["time_series"]),
            summary_notes=summary
        )
        db.add(result)
        db.commit()

        # Stage 6: Completed
        active_simulations[experiment_id]["progress_percent"] = 100
        active_simulations[experiment_id]["current_stage"] = "COMPLETED"
        active_simulations[experiment_id]["stage_message"] = "Simulation and trace analytics completed successfully!"
        active_simulations[experiment_id]["logs"].append(f"[{time.strftime('%H:%M:%S')}] Metrics persisted to database. Results ready.")
        active_simulations[experiment_id]["status"] = "COMPLETED"
        await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])
        await ws_manager.broadcast_global({
            "type": "SIMULATION_COMPLETED",
            "experiment_id": experiment_id,
            "exp_code": exp.exp_code,
            "name": exp.name,
            "throughput_kbps": metrics["throughput_kbps"],
            "pdr_percent": metrics["packet_delivery_ratio"]
        })

    except Exception as e:
        db.rollback()
        if exp:
            exp.status = "FAILED"
            db.commit()
        if experiment_id in active_simulations:
            active_simulations[experiment_id]["status"] = "FAILED"
            active_simulations[experiment_id]["error"] = str(e)
            active_simulations[experiment_id]["logs"].append(f"[{time.strftime('%H:%M:%S')}] ERROR: {str(e)}")
            await ws_manager.broadcast_sim(experiment_id, active_simulations[experiment_id])
    finally:
        db.close()
