import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  Activity,
  Zap,
  Clock,
  CheckCircle2,
  TrendingDown,
  Layers,
  ArrowRight,
  RefreshCw,
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Server
} from 'lucide-react';
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  AreaChart,
  Area
} from 'recharts';
import { api } from '../services/api';
import { subscribeGlobalTelemetry } from '../services/websocket';
import { DashboardSummary } from '../types';
import { useSimulationMode, ModeBadge, ModeSelector } from '../context/SimulationModeContext';
import { DEMO_DASHBOARD_SUMMARY, DEMO_EXPERIMENTS } from '../data/demoExperiments';

export const Dashboard: React.FC = () => {
  const { isDemo, isLive, setMode } = useSimulationMode();
  const [liveSummary, setLiveSummary] = useState<DashboardSummary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isLiveTelemetry, setIsLiveTelemetry] = useState(true);
  const [lastSyncTime, setLastSyncTime] = useState<string>(new Date().toLocaleTimeString());

  const fetchLiveSummary = async (showSpinner = false) => {
    if (showSpinner) setLoading(true);
    try {
      const data = await api.getDashboardSummary('realtime');
      setLiveSummary(data);
      setLastSyncTime(new Date().toLocaleTimeString());
      setError(null);
    } catch (err: any) {
      if (showSpinner) setError(err.message || 'Failed to connect to backend server');
    } finally {
      if (showSpinner) setLoading(false);
    }
  };

  useEffect(() => {
    if (isLive) {
      fetchLiveSummary(true);

      const unsubscribe = subscribeGlobalTelemetry(() => {
        fetchLiveSummary(false);
      });

      const interval = setInterval(() => {
        if (isLiveTelemetry) {
          fetchLiveSummary(false);
        }
      }, 3000);

      return () => {
        unsubscribe();
        clearInterval(interval);
      };
    }
  }, [isLive, isLiveTelemetry]);

  // Use appropriate data based on active mode
  const summary = isDemo ? DEMO_DASHBOARD_SUMMARY : liveSummary;
  const recentExps = isDemo ? DEMO_EXPERIMENTS.slice().reverse() : liveSummary?.recent_experiments || [];
  const kpis = summary?.kpis;

  // Traffic Load vs Performance dataset (Section 2)
  const trafficLoadData = [
    { load: 'Low Traffic (10 nodes)', throughput: 95.4, loss: 0.8, delay: 18.2 },
    { load: 'Medium Traffic (25-50 nodes)', throughput: 352.2, loss: 3.8, delay: 28.0 },
    { load: 'High Traffic (100 nodes)', throughput: 601.5, loss: 11.0, delay: 55.2 },
  ];

  // TCP vs UDP Comparison Data
  const protocolComparisonData = [
    {
      metric: 'Throughput (Kbps)',
      TCP: isDemo ? 361.6 : (liveSummary?.tcp_vs_udp?.tcp.throughput || 0),
      UDP: isDemo ? 505.1 : (liveSummary?.tcp_vs_udp?.udp.throughput || 0),
    },
    {
      metric: 'PDR (%)',
      TCP: isDemo ? 96.5 : (liveSummary?.tcp_vs_udp?.tcp.pdr || 0),
      UDP: isDemo ? 90.0 : (liveSummary?.tcp_vs_udp?.udp.pdr || 0),
    },
    {
      metric: 'Packet Loss (%)',
      TCP: isDemo ? 3.5 : (liveSummary?.tcp_vs_udp?.tcp.loss || 0),
      UDP: isDemo ? 10.0 : (liveSummary?.tcp_vs_udp?.udp.loss || 0),
    },
    {
      metric: 'Avg Delay (ms)',
      TCP: isDemo ? 28.6 : (liveSummary?.tcp_vs_udp?.tcp.delay || 0),
      UDP: isDemo ? 46.9 : (liveSummary?.tcp_vs_udp?.udp.delay || 0),
    },
  ];

  return (
    <div className="space-y-6">
      {/* Simulation Mode Switcher & Status Bar (Section 4) */}
      <div className="bg-white p-4 rounded-xl border border-[#CBD5E1] shadow-xs flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-blue-50 text-blue-600">
            <Activity className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-bold text-[#0F172A]">
                {isDemo ? 'DEMO MODE DASHBOARD' : 'LIVE NS-2 SIMULATION DASHBOARD'}
              </h2>
              <ModeBadge isDemo={isDemo} />
            </div>
            <p className="text-xs text-[#64748B]">
              {isDemo
                ? 'Sample Data — Not generated by NS-2. Completely standalone and offline.'
                : 'Real-time telemetry stream connected to the active NS-2 simulation backend.'}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <ModeSelector compact />
          {isLive && (
            <button
              onClick={() => fetchLiveSummary(true)}
              className="p-1.5 text-slate-500 hover:text-[#0F172A] rounded-lg border border-[#CBD5E1] hover:bg-slate-50"
              title="Refresh live telemetry"
            >
              <RefreshCw className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Mode Callout Banners (Section 1 & Section 3) */}
      {isDemo ? (
        <div className="p-4 bg-blue-50/80 border border-blue-200 rounded-xl flex items-center justify-between text-blue-900 text-xs">
          <div className="flex items-center gap-3">
            <span className="px-2.5 py-1 bg-blue-600 text-white font-mono font-bold rounded text-[11px] tracking-wide uppercase">
              DEMO MODE
            </span>
            <span>
              <strong>Sample Data — Not generated by NS-2:</strong> Displaying verified, internally consistent laboratory benchmark data. No external network services or NS-2 binaries required.
            </span>
          </div>
          <button
            onClick={() => {
              setMode('realtime');
              setError(null);
            }}
            className="text-xs font-semibold text-blue-700 hover:text-blue-900 underline whitespace-nowrap hidden sm:inline"
          >
            Switch to Live NS-2 →
          </button>
        </div>
      ) : !liveSummary?.is_ns2_available ? (
        <div className="p-5 bg-amber-50 border border-amber-300 rounded-xl text-amber-900 text-xs space-y-2">
          <div className="flex items-center gap-2 font-bold text-amber-950 text-sm">
            <AlertTriangle className="w-5 h-5 text-amber-600" />
            <span>LIVE SIMULATION UNAVAILABLE</span>
          </div>
          <p>
            NS-2 could not be executed. Native <code>ns</code> or <code>wsl ns</code> was not detected on your system path.
          </p>
          <div className="pt-2 flex items-center gap-3">
            <button
              onClick={() => {
                setMode('demo');
                setError(null);
              }}
              className="px-3.5 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg text-xs transition-colors shadow-xs"
            >
              Use Demo Mode (Sample Data)
            </button>
            <Link
              to="/settings"
              className="px-3 py-1.5 bg-white border border-amber-300 hover:bg-amber-100 text-amber-900 font-semibold rounded-lg text-xs transition-colors"
            >
              WSL NS-2 Setup Guide
            </Link>
          </div>
        </div>
      ) : (
        <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-xl flex items-center justify-between text-emerald-900 text-xs">
          <div className="flex items-center gap-3">
            <span className="px-2.5 py-1 bg-emerald-600 text-white font-mono font-bold rounded text-[11px] tracking-wide uppercase flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-white animate-pulse"></span>
              LIVE NS-2
            </span>
            <span>
              <strong>LIVE NS-2 SIMULATION ACTIVE:</strong> Real-time discrete-event engine pipeline connected.
            </span>
          </div>
          <span className="text-[11px] font-mono text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded">
            Live Telemetry Online
          </span>
        </div>
      )}

      {/* Real-Time Mode Empty State Callout */}
      {!isDemo && recentExps.length === 0 && (
        <div className="p-5 bg-gradient-to-r from-slate-50 to-blue-50/50 border border-slate-200 rounded-xl flex flex-wrap items-center justify-between gap-4 shadow-xs">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-blue-100 text-blue-700 flex items-center justify-center flex-shrink-0">
              <Activity className="w-5 h-5" />
            </div>
            <div>
              <h4 className="text-xs font-bold text-slate-800">No Live NS-2 Experiments Recorded in Database Yet</h4>
              <p className="text-[11px] text-slate-500 mt-0.5">
                Run an actual NS-2 simulation to generate discrete-event traces and populate live telemetry charts.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Link
              to="/simulate"
              className="px-3.5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold rounded-lg text-xs transition-colors shadow-xs"
            >
              + Run NS-2 Simulation
            </Link>
            <button
              type="button"
              onClick={() => setMode('demo')}
              className="px-3.5 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg text-xs transition-colors shadow-xs"
            >
              Use Demo Mode (View 9 Benchmarks)
            </button>
          </div>
        </div>
      )}

      {/* KPI Cards Grid (Section 2) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        {/* Total Experiments */}
        <div className="bg-white p-5 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-[#64748B] uppercase tracking-wider">
              {isDemo ? 'Demo Runs' : 'Total Runs'}
            </span>
            <div className="w-8 h-8 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center">
              <Layers className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-2xl font-bold text-[#0F172A]">{kpis?.total_experiments ?? 0}</span>
            <span className="text-xs text-slate-500 font-medium">experiments</span>
          </div>
          <p className="text-[11px] text-[#94A3B8] mt-1">
            {isDemo ? 'Predefined local records' : 'Recorded in SQLite'}
          </p>
        </div>

        {/* Avg Throughput */}
        <div className="bg-white p-5 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-[#64748B] uppercase tracking-wider">Throughput</span>
            <div className="w-8 h-8 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center">
              <Zap className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-2xl font-bold text-[#0F172A]">{kpis?.avg_throughput_kbps ?? 0}</span>
            <span className="text-xs text-emerald-600 font-semibold">Kbps</span>
          </div>
          <p className="text-[11px] text-[#94A3B8] mt-1">Average delivery rate</p>
        </div>

        {/* Avg Packet Loss */}
        <div className="bg-white p-5 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-[#64748B] uppercase tracking-wider">Packet Loss</span>
            <div className="w-8 h-8 rounded-lg bg-rose-50 text-rose-600 flex items-center justify-center">
              <TrendingDown className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-2xl font-bold text-[#0F172A]">{kpis?.avg_packet_loss_percent ?? 0}</span>
            <span className="text-xs text-rose-600 font-semibold">%</span>
          </div>
          <p className="text-[11px] text-[#94A3B8] mt-1">Bottleneck router drops</p>
        </div>

        {/* Avg Delay */}
        <div className="bg-white p-5 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-[#64748B] uppercase tracking-wider">Average Delay</span>
            <div className="w-8 h-8 rounded-lg bg-amber-50 text-amber-600 flex items-center justify-center">
              <Clock className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-2xl font-bold text-[#0F172A]">{kpis?.avg_delay_ms ?? 0}</span>
            <span className="text-xs text-amber-600 font-semibold">ms</span>
          </div>
          <p className="text-[11px] text-[#94A3B8] mt-1">End-to-end transmission</p>
        </div>

        {/* Packet Delivery Ratio */}
        <div className="bg-white p-5 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-[#64748B] uppercase tracking-wider">PDR</span>
            <div className="w-8 h-8 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center">
              <CheckCircle2 className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-2xl font-bold text-[#0F172A]">{kpis?.avg_pdr_percent ?? 0}</span>
            <span className="text-xs text-indigo-600 font-semibold">%</span>
          </div>
          <p className="text-[11px] text-[#94A3B8] mt-1">Packet Delivery Ratio</p>
        </div>
      </div>

      {/* Main Charts Row: Throughput vs Users & Packet Loss vs Users (Section 2) */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Chart 1: Throughput vs Users */}
        <div className="bg-white p-6 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-sm font-bold text-[#0F172A]">Throughput vs Users</h3>
              <p className="text-xs text-[#64748B]">Delivered campus bandwidth across client scaling</p>
            </div>
            <span className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded">Kbps vs Users</span>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={summary?.throughput_vs_users || []}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" />
                <XAxis dataKey="users" tick={{ fontSize: 11 }} label={{ value: 'Students (Users)', position: 'insideBottom', offset: -4, fontSize: 11 }} />
                <YAxis tick={{ fontSize: 11 }} label={{ value: 'Kbps', angle: -90, position: 'insideLeft', fontSize: 11 }} />
                <Tooltip contentStyle={{ backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: '8px', fontSize: '12px' }} />
                <Legend wrapperStyle={{ fontSize: '12px' }} />
                <Line type="monotone" dataKey="tcp" name="TCP NewReno" stroke="#2563EB" strokeWidth={2.5} activeDot={{ r: 6 }} connectNulls />
                <Line type="monotone" dataKey="udp" name="UDP CBR" stroke="#F59E0B" strokeWidth={2.5} activeDot={{ r: 6 }} connectNulls />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 2: Packet Loss vs Users */}
        <div className="bg-white p-6 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-sm font-bold text-[#0F172A]">Packet Loss vs Users</h3>
              <p className="text-xs text-[#64748B]">Queue drop rate progression as offered load scales</p>
            </div>
            <span className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded">Loss % vs Users</span>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={summary?.loss_vs_users || []}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" />
                <XAxis dataKey="users" tick={{ fontSize: 11 }} label={{ value: 'Students (Users)', position: 'insideBottom', offset: -4, fontSize: 11 }} />
                <YAxis tick={{ fontSize: 11 }} label={{ value: 'Loss %', angle: -90, position: 'insideLeft', fontSize: 11 }} />
                <Tooltip contentStyle={{ backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: '8px', fontSize: '12px' }} />
                <Legend wrapperStyle={{ fontSize: '12px' }} />
                <Area type="monotone" dataKey="tcp" name="TCP Loss %" stroke="#2563EB" fill="#DBEAFE" strokeWidth={2} connectNulls />
                <Area type="monotone" dataKey="udp" name="UDP Loss %" stroke="#DC2626" fill="#FEE2E2" strokeWidth={2} connectNulls />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Secondary Charts: Delay vs Users & TCP vs UDP & Traffic Load vs Performance (Section 2) */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Chart 3: Delay vs Users */}
        <div className="bg-white p-6 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-sm font-bold text-[#0F172A]">Delay vs Users</h3>
              <p className="text-xs text-[#64748B]">Average queuing latency (ms)</p>
            </div>
            <span className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded">Latency</span>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={summary?.delay_vs_users || []}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" />
                <XAxis dataKey="users" tick={{ fontSize: 11 }} />
                <YAxis tick={{ fontSize: 11 }} />
                <Tooltip contentStyle={{ backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: '8px', fontSize: '12px' }} />
                <Legend wrapperStyle={{ fontSize: '12px' }} />
                <Line type="monotone" dataKey="tcp" name="TCP Delay" stroke="#7C3AED" strokeWidth={2.5} connectNulls />
                <Line type="monotone" dataKey="udp" name="UDP Delay" stroke="#059669" strokeWidth={2.5} connectNulls />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 4: TCP vs UDP */}
        <div className="bg-white p-6 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-sm font-bold text-[#0F172A]">TCP vs UDP</h3>
              <p className="text-xs text-[#64748B]">Aggregate comparative metrics</p>
            </div>
            <span className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded">Protocols</span>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={protocolComparisonData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" />
                <XAxis dataKey="metric" tick={{ fontSize: 10 }} />
                <YAxis tick={{ fontSize: 11 }} />
                <Tooltip contentStyle={{ backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: '8px', fontSize: '12px' }} />
                <Legend wrapperStyle={{ fontSize: '12px' }} />
                <Bar dataKey="TCP" fill="#2563EB" radius={[4, 4, 0, 0]} />
                <Bar dataKey="UDP" fill="#F59E0B" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 5: Traffic Load vs Performance (Section 2) */}
        <div className="bg-white p-6 rounded-xl border border-[#E2E8F0] shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-sm font-bold text-[#0F172A]">Traffic Load vs Performance</h3>
              <p className="text-xs text-[#64748B]">Behavior across low, med, & high tiers</p>
            </div>
            <span className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded">Tiers</span>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={trafficLoadData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" />
                <XAxis dataKey="load" tick={{ fontSize: 9 }} />
                <YAxis tick={{ fontSize: 11 }} />
                <Tooltip contentStyle={{ backgroundColor: '#FFFFFF', borderColor: '#E2E8F0', borderRadius: '8px', fontSize: '12px' }} />
                <Legend wrapperStyle={{ fontSize: '12px' }} />
                <Bar dataKey="throughput" name="Throughput (Kbps)" fill="#10B981" radius={[4, 4, 0, 0]} />
                <Bar dataKey="loss" name="Loss (%)" fill="#EF4444" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Recent Experiments Table (with direct link to /experiments/:id) */}
      <div className="bg-white rounded-xl border border-[#E2E8F0] shadow-xs overflow-hidden">
        <div className="p-5 border-b border-[#E2E8F0] flex items-center justify-between">
          <div>
            <h3 className="text-sm font-bold text-[#0F172A]">
              {isDemo ? 'Predefined Demo Experiments' : 'Recent Simulation Experiments'}
            </h3>
            <p className="text-xs text-[#64748B]">
              {isDemo
                ? 'Standard verified laboratory benchmarks available for instant analysis'
                : 'Latest simulation runs processed by the metrics engine'}
            </p>
          </div>
          <Link
            to="/experiments"
            className="flex items-center gap-1 text-xs font-semibold text-blue-600 hover:text-blue-700"
          >
            <span>View All Records</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-[#F8FAFC] text-[#64748B] font-semibold border-b border-[#E2E8F0]">
              <tr>
                <th className="px-5 py-3">Code</th>
                <th className="px-5 py-3">Experiment Name</th>
                <th className="px-5 py-3">Mode</th>
                <th className="px-5 py-3">Students</th>
                <th className="px-5 py-3">Protocol</th>
                <th className="px-5 py-3">Throughput</th>
                <th className="px-5 py-3">Loss Rate</th>
                <th className="px-5 py-3">PDR</th>
                <th className="px-5 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#E2E8F0]">
              {recentExps.map((exp) => (
                <tr key={exp.id} className="hover:bg-slate-50 transition-colors">
                  <td className="px-5 py-3 font-mono font-semibold text-blue-700">
                    <Link to={`/experiments/${exp.id}`} className="hover:underline">
                      {exp.exp_code}
                    </Link>
                  </td>
                  <td className="px-5 py-3 font-medium text-[#0F172A]">
                    <div>{exp.name}</div>
                    <div className="text-[10px] text-slate-400">{exp.experiment_type} • {exp.data_rate}</div>
                  </td>
                  <td className="px-5 py-3">
                    <ModeBadge isDemo={exp.is_demo} />
                  </td>
                  <td className="px-5 py-3 text-[#475569]">{exp.users} nodes</td>
                  <td className="px-5 py-3">
                    <span className={`px-2 py-0.5 rounded font-semibold text-[10px] ${
                      exp.protocol === 'TCP' ? 'bg-blue-50 text-blue-700 border border-blue-200' : 'bg-amber-50 text-amber-700 border border-amber-200'
                    }`}>
                      {exp.protocol}
                    </span>
                  </td>
                  <td className="px-5 py-3 font-mono text-[#0F172A]">
                    {exp.result ? `${exp.result.throughput_kbps} Kbps` : '—'}
                  </td>
                  <td className="px-5 py-3 font-mono text-rose-600 font-semibold">
                    {exp.result ? `${exp.result.packet_loss_percent}%` : '—'}
                  </td>
                  <td className="px-5 py-3 font-mono text-emerald-700 font-semibold">
                    {exp.result ? `${exp.result.packet_delivery_ratio}%` : '—'}
                  </td>
                  <td className="px-5 py-3 text-right">
                    <Link
                      to={`/experiments/${exp.id}`}
                      className="text-xs font-semibold text-blue-600 hover:text-blue-800 hover:underline"
                    >
                      View Analytics
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
