import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  FileText,
  Download,
  CheckCircle2,
  Calendar,
  Layers,
  ArrowRight,
  RefreshCw,
  Search,
  BookOpen,
  AlertCircle
} from 'lucide-react';
import { useDataService } from '../services/dataService';
import { Experiment } from '../types';
import { ModeBadge, useSimulationMode } from '../context/SimulationModeContext';

export const Reports: React.FC = () => {
  const { mode, isDemo, setMode } = useSimulationMode();
  const dataService = useDataService();

  const [experiments, setExperiments] = useState<Experiment[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');

  const fetchExperiments = () => {
    setLoading(true);
    dataService
      .getExperiments({ limit: 50, search: search || undefined })
      .then(setExperiments)
      .catch(() => null)
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchExperiments();
  }, [search, mode]);

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header Banner */}
      <div className="bg-white p-6 rounded-xl border border-[#E2E8F0] shadow-xs flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-base font-bold text-[#0F172A]">
                {isDemo ? 'EduNet Analyzer: Demo Experiment Report Hub' : 'EduNet Analyzer: NS-2 Network Performance Report Hub'}
              </h2>
              <ModeBadge isDemo={isDemo} />
            </div>
            <p className="text-xs text-[#64748B]">
              {isDemo
                ? 'Generate publication-grade academic laboratory reports from predefined laboratory benchmarks'
                : 'Generate academic laboratory reports compiled from live NS-2 discrete-event simulation records'}
            </p>
          </div>
        </div>

        {/* Search */}
        <div className="relative min-w-[240px]">
          <input
            type="text"
            placeholder={isDemo ? 'Search demo reports...' : 'Search live reports...'}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-9 pr-3 py-1.5 text-xs rounded-lg border border-[#CBD5E1] focus:ring-2 focus:ring-blue-500 bg-[#F8FAFC]"
          />
          <Search className="w-4 h-4 text-slate-400 absolute left-2.5 top-2" />
        </div>
      </div>

      {/* Mode Specific Watermark Callout */}
      {isDemo ? (
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-xl text-xs text-blue-900 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="px-2.5 py-1 bg-blue-600 text-white font-mono font-bold rounded text-[11px] uppercase tracking-wide">
              DEMO DATA
            </span>
            <span>
              <strong>Notice:</strong> These results are predefined demonstration data and were not generated by a live NS-2 simulation.
            </span>
          </div>
          <button
            onClick={() => setMode('realtime')}
            className="text-xs font-semibold text-blue-700 hover:text-blue-900 underline hidden sm:inline"
          >
            Switch to Live NS-2 Mode →
          </button>
        </div>
      ) : (
        <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-xl text-xs text-emerald-900 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="px-2.5 py-1 bg-emerald-600 text-white font-mono font-bold rounded text-[11px] uppercase tracking-wide flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-white animate-pulse"></span>
              LIVE NS-2 SIMULATION
            </span>
            <span>
              <strong>Verified Live Telemetry:</strong> All reports below reflect actual discrete-event simulation runs executed by NS-2 and parsed from simulation traces.
            </span>
          </div>
          <button
            onClick={() => setMode('demo')}
            className="text-xs font-semibold text-emerald-700 hover:text-emerald-900 underline hidden sm:inline"
          >
            Switch to Demo Mode →
          </button>
        </div>
      )}

      {/* PDF Report Structure Guide */}
      <div className="bg-slate-50 p-6 rounded-xl border border-slate-200">
        <div className="flex items-center gap-2 text-xs font-bold text-slate-800 uppercase tracking-wider mb-2">
          <BookOpen className="w-4 h-4 text-blue-600" />
          <span>Academic Laboratory Report Standard Structure</span>
        </div>
        <p className="text-xs text-slate-600 leading-relaxed mb-3">
          Every report document follows the university curriculum standards for Computer Networks & IP laboratory courseware:
        </p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-[11px] text-slate-800 font-medium font-mono">
          <div className="bg-white p-2.5 rounded-lg border border-slate-200">1. Experiment Header & Metadata</div>
          <div className="bg-white p-2.5 rounded-lg border border-slate-200">2. Network Topology & Links</div>
          <div className="bg-white p-2.5 rounded-lg border border-slate-200">3. Throughput & Delay Metrics</div>
          <div className="bg-white p-2.5 rounded-lg border border-slate-200">4. Conclusions & Signature Block</div>
        </div>
      </div>

      {/* Reports Listing */}
      <div className="bg-white rounded-xl border border-[#E2E8F0] shadow-xs overflow-hidden">
        <div className="p-5 border-b border-[#E2E8F0] flex items-center justify-between">
          <h3 className="text-sm font-bold text-[#0F172A]">Available Experiment Reports</h3>
          <span className="text-xs text-slate-500 font-medium">{experiments.length} Records</span>
        </div>

        <div className="divide-y divide-[#E2E8F0]">
          {loading && (
            <div className="py-8 text-center text-slate-500 text-xs">
              <RefreshCw className="w-5 h-5 animate-spin mx-auto text-blue-600 mb-2" />
              Loading report documents...
            </div>
          )}

          {!loading && experiments.length === 0 && (
            <div className="py-12 text-center text-slate-500 text-xs space-y-2">
              <p className="font-semibold text-slate-700">
                {isDemo
                  ? 'No demo experiment reports match your search query.'
                  : 'No live NS-2 simulations recorded in the database yet.'}
              </p>
              {!isDemo && (
                <div className="pt-2 flex items-center justify-center gap-3">
                  <button
                    onClick={() => setMode('demo')}
                    className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg text-xs"
                  >
                    Use Demo Mode (Sample Data)
                  </button>
                  <Link
                    to="/simulate"
                    className="px-3 py-1.5 bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 font-semibold rounded-lg text-xs"
                  >
                    Run Live Simulation
                  </Link>
                </div>
              )}
            </div>
          )}

          {!loading &&
            experiments.map((exp) => (
              <div
                key={exp.id}
                className="p-5 flex flex-wrap items-center justify-between gap-4 hover:bg-slate-50 transition-colors"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-bold text-xs text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-100">
                      {exp.exp_code}
                    </span>
                    <span className="text-sm font-bold text-[#0F172A]">{exp.name}</span>
                    <ModeBadge isDemo={exp.is_demo} />
                    <span
                      className={`text-[10px] font-semibold px-2 py-0.5 rounded ${
                        exp.protocol === 'TCP' ? 'bg-blue-50 text-blue-700' : 'bg-amber-50 text-amber-700'
                      }`}
                    >
                      {exp.protocol}
                    </span>
                  </div>
                  <p className="text-xs text-[#64748B]">
                    {exp.experiment_type} • {exp.users} Students • Bottleneck: {exp.data_rate} • Duration:{' '}
                    {exp.simulation_time}s
                  </p>
                  <div className="flex items-center gap-4 text-[11px] text-slate-500 pt-1 font-mono">
                    <span>
                      TP: <strong>{exp.result?.throughput_kbps ?? 0} Kbps</strong>
                    </span>
                    <span>
                      Loss: <strong className="text-rose-600">{exp.result?.packet_loss_percent ?? 0}%</strong>
                    </span>
                    <span>
                      PDR:{' '}
                      <strong className="text-emerald-700">{exp.result?.packet_delivery_ratio ?? 0}%</strong>
                    </span>
                    <span>
                      Delay: <strong>{exp.result?.average_delay_ms ?? 0} ms</strong>
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <a
                    href={dataService.getReportCsvUrl(exp.id)}
                    download
                    className="flex items-center gap-1.5 px-3 py-2 text-xs font-semibold rounded-lg bg-white border border-[#CBD5E1] text-[#0F172A] hover:bg-slate-50 shadow-xs"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download CSV</span>
                  </a>

                  <a
                    href={dataService.getReportPdfUrl(exp.id)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-1.5 px-4 py-2 text-xs font-semibold rounded-lg bg-blue-600 text-white hover:bg-blue-700 shadow-sm shadow-blue-200"
                  >
                    <FileText className="w-3.5 h-3.5" />
                    <span>Academic PDF</span>
                  </a>
                </div>
              </div>
            ))}
        </div>
      </div>
    </div>
  );
};
